language: cpp

compiler:
  - clang
install:
  - sudo apt-get update
  - apt-cache info libc++-dev
  - sudo apt-get install -y libc++-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
